server:
  port: 8084

spring:
  application:
    name: parking-space-service

  datasource:
    url: jdbc:mysql://localhost:3306/Parking_space_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Ijse@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: default

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE



#  http://localhost:8084/api/parking-spaces/register
#  {
#    "location": "Colombo Fort",
#    "ownerId": 101,
#    "status": "AVAILABLE"
#  }
# get=
#  http://localhost:8084/api/parking-spaces
# update=
#  http://localhost:8084/api/parking-spaces/1/status?status=OCCUPIED
# delete=
#  http://localhost:8084/api/parking-spaces/1


#parking Space details
#  http://localhost:8084/api/parking-spaces/details/1/details
#  {
#    "numberPlate": "CAX-1234",
#    "entryTime": "2025-06-22T08:30:00",
#    "exitTime": "2025-06-22T10:00:00"
#  }
#get=
#  http://localhost:8084/api/parking-spaces/details/1/details
#delete=
#  http://localhost:8084/api/parking-spaces/details/3

